name: annotation_error
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy==1.18.1
  - pandas==1.0.1
  - biopython==1.76
  - scikit-learn==0.20.0
  - matplotlib==3.1.3
  - beautifulsoup4==4.9.3
  - cd-hit==4.8.1
  - blast==2.5.0
  - muscle==3.8.1551
  - tensorflow==1.15.0
  - seaborn
  - jupyter
  - psutil
  - requests
  - fftw
  - cython
  - tqdm
  - pip
  - pip:
    - python-dotenv
    - alfpy==1.0.6
