name: py37
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy==1.18.1
  - pandas==1.0.1
  - biopython==1.76
  - scikit-learn==0.20.0
  - matplotlib==3.1.3
  - seaborn
  - jupyter
  - psutil
  - requests
  - fftw
  - cython
  - cd-hit
  - muscle
  - tensorflow=1.15.0
  - tqdm
  - pip
  - pip:
    - python-dotenv
    - alfpy
